"""Deployment config file generator.

Reads a DeployProfile and produces the appropriate infrastructure configuration
files for the selected target (docker, docker-compose, kubernetes, ec2, ecs, lambda).

Files are written into a `deploy/` sub-directory of the project root so they
don't pollute the workspace until the developer is ready to use them.

Current targets: docker, docker-compose, kubernetes, ec2, ecs-fargate, lambda
Planned targets (see DEPLOYER_ROADMAP.md Phase 3):
  fly.io (fly.toml), railway (railway.json), cloud-run (service.yaml),
  systemd (<app>.service), process (run.sh + .env.example), helm (Chart.yaml)
"""
from __future__ import annotations

import json
import textwrap
from pathlib import Path

from zonny_core.deploy.profile import DeployProfile

# ── Shared helpers ─────────────────────────────────────────────────────────────

def _env_block_dockerfile(env_vars: list[str]) -> str:
    if not env_vars:
        return ""
    return "\n" + "\n".join(f'ENV {v}=""' for v in env_vars)


def _env_block_compose(env_vars: list[str]) -> str:
    if not env_vars:
        return ""
    lines = "\n".join(f"      - {v}" for v in env_vars)
    return f"\n    environment:\n{lines}"


def _db_service_compose(db_type: str) -> str:
    configs = {
        "postgresql": textwrap.dedent("""\
              db:
                image: postgres:16-alpine
                environment:
                  - POSTGRES_USER=app
                  - POSTGRES_PASSWORD=secret
                  - POSTGRES_DB=appdb
                volumes:
                  - db_data:/var/lib/postgresql/data
                healthcheck:
                  test: ["CMD-SHELL", "pg_isready -U app"]
                  interval: 10s
                  timeout: 5s
                  retries: 5
        """),
        "mysql": textwrap.dedent("""\
              db:
                image: mysql:8-debian
                environment:
                  - MYSQL_ROOT_PASSWORD=secret
                  - MYSQL_DATABASE=appdb
                volumes:
                  - db_data:/var/lib/mysql
        """),
        "mongodb": textwrap.dedent("""\
              db:
                image: mongo:7
                volumes:
                  - db_data:/data/db
        """),
        "redis": textwrap.dedent("""\
              cache:
                image: redis:7-alpine
                volumes:
                  - cache_data:/data
        """),
    }
    return configs.get(db_type, "")


# ── Public API ─────────────────────────────────────────────────────────────────

def generate(profile: DeployProfile, target: str, out_dir: Path) -> list[Path]:
    """Generate config files for *target* and write them to *out_dir*.

    Returns the list of paths that were written.
    """
    generators = {
        "docker":           _generate_docker,
        "docker-compose":   _generate_compose,
        "kubernetes":       _generate_kubernetes,
        "ec2":              _generate_ec2,
        "ecs-fargate":      _generate_ecs,
        "lambda":           _generate_lambda,
        "fly.io":           _generate_flyio,
        "railway":          _generate_railway,
        "cloud-run":        _generate_cloudrun,
        "systemd":          _generate_systemd,
        "process":          _generate_process,
        "helm":             _generate_helm,
    }
    fn = generators.get(target)
    if fn is None:
        raise ValueError(f"Unknown deploy target '{target}'. Choose from: {', '.join(generators)}")
    out_dir.mkdir(parents=True, exist_ok=True)
    return fn(profile, out_dir)


# ── Target generators ──────────────────────────────────────────────────────────

def _generate_docker(p: DeployProfile, out: Path) -> list[Path]:
    base_image = {
        "python":     f"python:{p.runtime}-slim",
        "node":       f"node:{p.runtime}-alpine",
        "typescript": f"node:{p.runtime}-alpine",
        "java":       f"eclipse-temurin:{p.runtime}-jre",
        "go":         f"golang:{p.runtime}-alpine",
        "ruby":       f"ruby:{p.runtime}-alpine",
        "rust":       f"rust:{p.runtime}-slim",
        "php":        f"php:{p.runtime}-fpm-alpine",
        "dotnet":     f"mcr.microsoft.com/dotnet/aspnet:{p.runtime}",
        "dart":       f"dart:{p.runtime}",
        "static":     "nginx:alpine",
    }.get(p.language, "ubuntu:22.04")

    dockerfile = textwrap.dedent(f"""\
        # Generated by Zonny — zonny deploy generate --target docker
        FROM {base_image} AS build
        WORKDIR /app

        # Install dependencies
        COPY {"requirements.txt ." if p.language == "python" else "package*.json ." if p.language == "node" else ". ."}
        RUN {p.build_cmd}

        FROM {base_image}
        WORKDIR /app

        # Run as non-root user
        RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser
        COPY --from=build /app /app
        USER appuser

        EXPOSE {p.port}
        HEALTHCHECK --interval=30s --timeout=5s CMD curl -f http://localhost:{p.port}/healthz || exit 1
        {_env_block_dockerfile(p.env_vars)}
        CMD {json.dumps(p.start_cmd.split())}
    """)

    dockerignore = textwrap.dedent("""\
        .git
        .gitignore
        .env
        __pycache__
        *.pyc
        node_modules
        dist
        .venv
        *.test.*
        README.md
        .zonny/
    """)

    paths = []
    (out / "Dockerfile").write_text(dockerfile, encoding="utf-8")
    paths.append(out / "Dockerfile")
    (out / ".dockerignore").write_text(dockerignore, encoding="utf-8")
    paths.append(out / ".dockerignore")
    return paths


def _generate_compose(p: DeployProfile, out: Path) -> list[Path]:
    db_services = ""
    volume_names = []
    depends = ""
    for db in p.databases:
        db_services += _db_service_compose(db.type)
        if db.type in ("postgresql", "mysql", "mongodb"):
            volume_names.append("db_data")
            depends = "\n    depends_on:\n      db:\n        condition: service_healthy"
        elif db.type == "redis":
            volume_names.append("cache_data")
            depends += "\n    depends_on:\n      - cache"

    volumes_section = ""
    if volume_names:
        volumes_section = "\nvolumes:\n" + "\n".join(f"  {v}:" for v in set(volume_names))

    nginx_service = ""
    if p.has_static:
        nginx_service = textwrap.dedent(f"""\
              nginx:
                image: nginx:alpine
                ports:
                  - "80:80"
                volumes:
                  - ./nginx.conf:/etc/nginx/nginx.conf:ro
                depends_on:
                  - app
        """)

    compose = textwrap.dedent(f"""\
        # Generated by Zonny — zonny deploy generate --target docker-compose
        version: "3.9"

        services:
          app:
            build: .
            ports:
              - "{p.port}:{p.port}"
            env_file:
              - .env{_env_block_compose(p.env_vars)}{depends}
            restart: unless-stopped
        {db_services}{nginx_service}{volumes_section}
    """)

    path = out / "docker-compose.yml"
    path.write_text(compose, encoding="utf-8")
    return [path]


def _generate_kubernetes(p: DeployProfile, out: Path) -> list[Path]:
    k8s_dir = out / "k8s"
    k8s_dir.mkdir(exist_ok=True)
    paths = []

    # Deployment
    deployment = textwrap.dedent(f"""\
        # Generated by Zonny — zonny deploy generate --target kubernetes
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {p.project}
          labels:
            app: {p.project}
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: {p.project}
          template:
            metadata:
              labels:
                app: {p.project}
            spec:
              containers:
                - name: {p.project}
                  image: {p.project}:latest
                  ports:
                    - containerPort: {p.port}
                  resources:
                    requests:
                      memory: "256Mi"
                      cpu: "100m"
                    limits:
                      memory: "{p.estimated_memory}"
                      cpu: "500m"
                  envFrom:
                    - configMapRef:
                        name: {p.project}-config
                  livenessProbe:
                    httpGet:
                      path: /healthz
                      port: {p.port}
                    initialDelaySeconds: 30
                    periodSeconds: 10
                  readinessProbe:
                    httpGet:
                      path: /healthz
                      port: {p.port}
                    initialDelaySeconds: 5
                    periodSeconds: 5
    """)
    (k8s_dir / "deployment.yaml").write_text(deployment, encoding="utf-8")
    paths.append(k8s_dir / "deployment.yaml")

    # Service
    service = textwrap.dedent(f"""\
        apiVersion: v1
        kind: Service
        metadata:
          name: {p.project}-svc
        spec:
          selector:
            app: {p.project}
          ports:
            - protocol: TCP
              port: 80
              targetPort: {p.port}
          type: ClusterIP
    """)
    (k8s_dir / "service.yaml").write_text(service, encoding="utf-8")
    paths.append(k8s_dir / "service.yaml")

    # ConfigMap
    cm_data = "\n".join(f'  {v}: ""' for v in p.env_vars)
    configmap = textwrap.dedent(f"""\
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: {p.project}-config
        data:
        {cm_data}
    """)
    (k8s_dir / "configmap.yaml").write_text(configmap, encoding="utf-8")
    paths.append(k8s_dir / "configmap.yaml")

    # Ingress
    ingress = textwrap.dedent(f"""\
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: {p.project}-ingress
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
        spec:
          rules:
            - host: {p.project}.example.com
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: {p.project}-svc
                        port:
                          number: 80
    """)
    (k8s_dir / "ingress.yaml").write_text(ingress, encoding="utf-8")
    paths.append(k8s_dir / "ingress.yaml")

    return paths


def _generate_ec2(p: DeployProfile, out: Path) -> list[Path]:
    provision = textwrap.dedent(f"""\
        #!/bin/bash
        # Generated by Zonny — zonny deploy generate --target ec2
        set -e
        apt-get update -y && apt-get upgrade -y
        apt-get install -y git curl build-essential

        # Install runtime
        {_ec2_runtime_install(p)}

        # Clone and setup app
        cd /opt
        git clone $APP_REPO {p.project}
        cd {p.project}
        {p.build_cmd}

        # Copy systemd service
        cp app.service /etc/systemd/system/{p.project}.service
        systemctl daemon-reload
        systemctl enable {p.project}
        systemctl start {p.project}

        echo "Deployment complete!"
    """)

    service_unit = textwrap.dedent(f"""\
        [Unit]
        Description={p.project} app service
        After=network.target

        [Service]
        Type=simple
        User=www-data
        WorkingDirectory=/opt/{p.project}
        ExecStart={p.start_cmd}
        Restart=always
        RestartSec=5
        EnvironmentFile=/etc/{p.project}.env

        [Install]
        WantedBy=multi-user.target
    """)

    paths = []
    (out / "provision.sh").write_text(provision, encoding="utf-8")
    paths.append(out / "provision.sh")
    (out / "app.service").write_text(service_unit, encoding="utf-8")
    paths.append(out / "app.service")
    return paths


def _ec2_runtime_install(p: DeployProfile) -> str:
    if p.language == "python":
        return f"apt-get install -y python{p.runtime} python3-pip python3-venv"
    if p.language in ("node", "typescript"):
        return f"curl -fsSL https://deb.nodesource.com/setup_{p.runtime}.x | bash - && apt-get install -y nodejs"
    if p.language == "java":
        return f"apt-get install -y openjdk-{p.runtime}-jdk"
    if p.language == "go":
        return f"wget https://go.dev/dl/go{p.runtime}.linux-amd64.tar.gz && tar -C /usr/local -xzf go*.tar.gz && export PATH=$PATH:/usr/local/go/bin"
    if p.language == "rust":
        return "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source $HOME/.cargo/env"
    if p.language == "php":
        return f"apt-get install -y php{p.runtime} php{p.runtime}-fpm php{p.runtime}-mbstring php{p.runtime}-xml curl && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
    if p.language == "dotnet":
        return f"wget https://dot.net/v1/dotnet-install.sh && chmod +x dotnet-install.sh && ./dotnet-install.sh --channel {p.runtime} && export DOTNET_ROOT=$HOME/.dotnet && export PATH=$PATH:$HOME/.dotnet"
    if p.language == "dart":
        return "apt-get install -y apt-transport-https && wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && aptitude install -y dart"
    if p.language == "ruby":
        return f"apt-get install -y ruby{p.runtime} ruby{p.runtime}-dev bundler"
    return ""


def _generate_ecs(p: DeployProfile, out: Path) -> list[Path]:
    task_def = {
        "family": p.project,
        "networkMode": "awsvpc",
        "requiresCompatibilities": ["FARGATE"],
        "cpu": "256",
        "memory": p.estimated_memory.replace("MB", "").replace("GB", "000"),
        "executionRoleArn": "arn:aws:iam::ACCOUNT_ID:role/ecsTaskExecutionRole",
        "containerDefinitions": [
            {
                "name": p.project,
                "image": f"ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/{p.project}:latest",
                "portMappings": [{"containerPort": p.port, "protocol": "tcp"}],
                "environment": [{"name": v, "value": ""} for v in p.env_vars],
                "logConfiguration": {
                    "logDriver": "awslogs",
                    "options": {
                        "awslogs-group": f"/ecs/{p.project}",
                        "awslogs-region": "us-east-1",
                        "awslogs-stream-prefix": "ecs",
                    },
                },
                "healthCheck": {
                    "command": ["CMD-SHELL", f"curl -f http://localhost:{p.port}/healthz || exit 1"],
                    "interval": 30,
                    "timeout": 5,
                    "retries": 3,
                },
            }
        ],
    }

    ecs_service = {
        "cluster": "default",
        "serviceName": p.project,
        "taskDefinition": p.project,
        "launchType": "FARGATE",
        "desiredCount": 2,
        "networkConfiguration": {
            "awsvpcConfiguration": {
                "subnets": ["subnet-XXXXXXXX"],
                "securityGroups": ["sg-XXXXXXXX"],
                "assignPublicIp": "ENABLED",
            }
        },
    }

    paths = []
    td_path = out / "task-definition.json"
    td_path.write_text(json.dumps(task_def, indent=2), encoding="utf-8")
    paths.append(td_path)
    svc_path = out / "ecs-service.json"
    svc_path.write_text(json.dumps(ecs_service, indent=2), encoding="utf-8")
    paths.append(svc_path)
    return paths


def _generate_lambda(p: DeployProfile, out: Path) -> list[Path]:
    if p.language == "python":
        handler = textwrap.dedent(f"""\
            # Generated by Zonny — Lambda handler wrapper for {p.framework or 'Python'} app
            # Wraps your {p.framework or 'ASGI/WSGI'} app for AWS Lambda + API Gateway

            try:
                from mangum import Mangum  # ASGI adapter
                from {p.entry_point.replace('.py', '')} import app as _app
                handler = Mangum(_app)
            except ImportError:
                import json
                def handler(event, context):
                    return {{'statusCode': 200, 'body': json.dumps({{'status': 'ok'}})}}
        """)
    elif p.language == "node":
        handler = textwrap.dedent(f"""\
            // Generated by Zonny — Lambda handler wrapper
            const serverless = require('serverless-http');
            const app = require('./{p.entry_point.replace('.js', '')}');
            module.exports.handler = serverless(app);
        """)
    else:
        handler = f"# Lambda handler — manually adapt {p.entry_point} for your runtime\n"

    sam_template = textwrap.dedent(f"""\
        AWSTemplateFormatVersion: '2010-09-09'
        Transform: AWS::Serverless-2016-10-31
        Description: {p.project} — deployed via AWS SAM (generated by Zonny)

        Globals:
          Function:
            Timeout: 30
            MemorySize: 256

        Resources:
          {p.project.title().replace('-', '')}Function:
            Type: AWS::Serverless::Function
            Properties:
              CodeUri: ./
              Handler: handler.handler
              Runtime: {"python" + p.runtime if p.language == "python" else "nodejs" + p.runtime + ".x" if p.language == "node" else "provided.al2"}
              Events:
                Api:
                  Type: Api
                  Properties:
                    Path: /{{proxy+}}
                    Method: ANY
              Environment:
                Variables:
                  {chr(10).join(f'  {v}: !Sub "${{{v}}}"' for v in p.env_vars) or '  {}'}
    """)

    paths = []
    handler_path = out / "handler.py" if p.language == "python" else out / "handler.js"
    handler_path.write_text(handler, encoding="utf-8")
    paths.append(handler_path)
    template_path = out / "template.yaml"
    template_path.write_text(sam_template, encoding="utf-8")
    paths.append(template_path)
    return paths


def _generate_flyio(p: DeployProfile, out: Path) -> list[Path]:
    """Generate fly.toml for Fly.io deployment."""
    # Normalise memory: "512MB" -> "512mb", "1GB" -> "1gb"
    memory = p.estimated_memory.lower()

    env_section = ""
    if p.env_vars:
        env_lines = "\n".join(f'  {v} = ""' for v in p.env_vars)
        env_section = f"\n[env]\n{env_lines}\n"

    fly_toml = textwrap.dedent(f"""\
        # Generated by Zonny — zonny deploy generate --target fly.io
        app = "{p.project}"
        primary_region = "iad"

        [build]

        [http_service]
          internal_port = {p.port}
          force_https = true
          auto_stop_machines = true
          auto_start_machines = true
          min_machines_running = 0
          processes = ["app"]

        [[vm]]
          memory = "{memory}"
          cpu_kind = "shared"
          cpus = 1
        {env_section}"""
    )

    path = out / "fly.toml"
    path.write_text(fly_toml, encoding="utf-8")
    return [path]


def _generate_railway(p: DeployProfile, out: Path) -> list[Path]:
    """Generate railway.json for Railway deployment."""
    config = {
        "$schema": "https://railway.app/railway.schema.json",
        "build": {"builder": "NIXPACKS"},
        "deploy": {
            "startCommand": p.start_cmd,
            "restartPolicyType": "ON_FAILURE",
            "restartPolicyMaxRetries": 10,
        },
    }

    # Also write a nixpacks.toml so Railway knows the start command explicitly
    nixpacks = textwrap.dedent(f"""\
        # Generated by Zonny — nixpacks.toml for Railway
        [phases.build]
        cmds = [{json.dumps(p.build_cmd)}]

        [start]
        cmd = {json.dumps(p.start_cmd)}
    """)

    paths = []
    rj = out / "railway.json"
    rj.write_text(json.dumps(config, indent=2), encoding="utf-8")
    paths.append(rj)
    np_ = out / "nixpacks.toml"
    np_.write_text(nixpacks, encoding="utf-8")
    paths.append(np_)
    return paths


def _generate_cloudrun(p: DeployProfile, out: Path) -> list[Path]:
    """Generate service.yaml (Cloud Run / Knative) + cloudbuild.yaml."""
    mem_k8s = p.estimated_memory.replace("MB", "Mi").replace("GB", "Gi")

    env_block = ""
    if p.env_vars:
        items = "\n".join(
            f"            - name: {v}\n              value: \"\""
            for v in p.env_vars
        )
        env_block = f"\n          env:\n{items}"

    service_yaml = textwrap.dedent(f"""\
        # Generated by Zonny — zonny deploy generate --target cloud-run
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: {p.project}
          annotations:
            run.googleapis.com/ingress: all
        spec:
          template:
            metadata:
              annotations:
                autoscaling.knative.dev/maxScale: "10"
                run.googleapis.com/cpu-throttling: "false"
            spec:
              containerConcurrency: 80
              timeoutSeconds: 300
              containers:
                - image: gcr.io/PROJECT_ID/{p.project}:latest
                  ports:
                    - containerPort: {p.port}
                  resources:
                    limits:
                      memory: {mem_k8s}
                      cpu: "1"{env_block}
    """)

    cloudbuild = textwrap.dedent(f"""\
        # Generated by Zonny — Cloud Build pipeline for {p.project}
        steps:
          - name: 'gcr.io/cloud-builders/docker'
            args: ['build', '-t', 'gcr.io/$PROJECT_ID/{p.project}:$COMMIT_SHA', '.']
          - name: 'gcr.io/cloud-builders/docker'
            args: ['push', 'gcr.io/$PROJECT_ID/{p.project}:$COMMIT_SHA']
          - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
            entrypoint: gcloud
            args:
              - run
              - deploy
              - {p.project}
              - --image=gcr.io/$PROJECT_ID/{p.project}:$COMMIT_SHA
              - --region=us-central1
              - --platform=managed
        images:
          - 'gcr.io/$PROJECT_ID/{p.project}:$COMMIT_SHA'
    """)

    paths = []
    (out / "service.yaml").write_text(service_yaml, encoding="utf-8")
    paths.append(out / "service.yaml")
    (out / "cloudbuild.yaml").write_text(cloudbuild, encoding="utf-8")
    paths.append(out / "cloudbuild.yaml")
    return paths


def _generate_systemd(p: DeployProfile, out: Path) -> list[Path]:
    """Generate a hardened systemd unit file + install-service.sh."""
    exec_start = _systemd_exec_start(p)

    service_unit = textwrap.dedent(f"""\
        # Generated by Zonny — zonny deploy generate --target systemd
        [Unit]
        Description={p.project} application service
        Documentation=https://github.com/user/{p.project}
        After=network-online.target
        Wants=network-online.target

        [Service]
        Type=simple
        User=www-data
        Group=www-data
        WorkingDirectory=/opt/{p.project}
        ExecStart={exec_start}
        ExecReload=/bin/kill -HUP $MAINPID
        Restart=on-failure
        RestartSec=5s
        StartLimitBurst=5
        StartLimitIntervalSec=60s
        EnvironmentFile=-/etc/{p.project}.env
        StandardOutput=journal
        StandardError=journal
        SyslogIdentifier={p.project}

        # Security hardening
        NoNewPrivileges=true
        PrivateTmp=true
        ProtectSystem=strict
        ReadWritePaths=/opt/{p.project}

        [Install]
        WantedBy=multi-user.target
    """)

    install_sh = textwrap.dedent(f"""\
        #!/bin/bash
        # Generated by Zonny — install {p.project} as a systemd service
        set -e

        APP_DIR=/opt/{p.project}
        SERVICE_FILE=/etc/systemd/system/{p.project}.service

        echo "[1/4] Copying service file..."
        sudo cp {p.project}.service "$SERVICE_FILE"
        sudo chmod 644 "$SERVICE_FILE"

        echo "[2/4] Creating app directory..."
        sudo mkdir -p "$APP_DIR"
        sudo chown www-data:www-data "$APP_DIR"

        echo "[3/4] Enabling and starting service..."
        sudo systemctl daemon-reload
        sudo systemctl enable {p.project}
        sudo systemctl start {p.project}

        echo "[4/4] Done! Status: sudo systemctl status {p.project}"
    """)

    paths = []
    (out / f"{p.project}.service").write_text(service_unit, encoding="utf-8")
    paths.append(out / f"{p.project}.service")
    (out / "install-service.sh").write_text(install_sh, encoding="utf-8")
    paths.append(out / "install-service.sh")
    return paths


def _systemd_exec_start(p: DeployProfile) -> str:
    """Return a fully qualified ExecStart command for systemd."""
    if p.language == "python":
        return f"/opt/{p.project}/.venv/bin/{p.start_cmd}"
    if p.language in ("node", "typescript"):
        return f"/usr/bin/{p.start_cmd}"
    if p.language == "go":
        return f"/opt/{p.project}/bin/{p.project}"
    if p.language == "java":
        return f"/usr/bin/java -jar /opt/{p.project}/app.jar"
    if p.language == "rust":
        return f"/opt/{p.project}/target/release/{p.project}"
    if p.language == "dotnet":
        return f"/usr/bin/dotnet /opt/{p.project}/out/{p.project}.dll"
    if p.language == "php":
        return f"/usr/bin/php /opt/{p.project}/artisan serve --host=0.0.0.0 --port={p.port}"
    if p.language == "dart":
        return f"/usr/bin/dart run /opt/{p.project}/bin/server.dart"
    return p.start_cmd


def _generate_process(p: DeployProfile, out: Path) -> list[Path]:
    """Generate run.sh + .env.example for plain process deployment (no containers)."""
    setup_cmds = _process_setup_cmds(p)

    run_sh = textwrap.dedent(f"""\
        #!/bin/bash
        # Generated by Zonny — run {p.project} without containers
        # Usage:  chmod +x run.sh && ./run.sh
        set -e

        # ── Load environment ────────────────────────────────────────────────
        if [ -f .env ]; then
          set -a; source .env; set +a
        fi

        # ── Install dependencies ─────────────────────────────────────────────
        echo "[1/2] Installing dependencies..."
        {setup_cmds}

        # ── Start app ────────────────────────────────────────────────────────
        echo "[2/2] Starting {p.project} on port {p.port}..."
        exec {p.start_cmd}
    """)

    env_lines = "\n".join(f"{v}=" for v in p.env_vars) if p.env_vars else "# No environment variables detected"
    env_example = f"# Generated by Zonny — copy to .env and fill in values\n{env_lines}\n"

    # Windows batch equivalent
    win_setup = _process_setup_cmds_windows(p)
    run_bat = textwrap.dedent(f"""\
        @echo off
        REM Generated by Zonny — run {p.project} without containers (Windows)
        REM Usage: run.bat

        REM Install dependencies
        echo [1/2] Installing dependencies...
        {win_setup}

        REM Start app
        echo [2/2] Starting {p.project} on port {p.port}...
        {p.start_cmd}
    """)

    paths = []
    (out / "run.sh").write_text(run_sh, encoding="utf-8")
    paths.append(out / "run.sh")
    (out / "run.bat").write_text(run_bat, encoding="utf-8")
    paths.append(out / "run.bat")
    (out / ".env.example").write_text(env_example, encoding="utf-8")
    paths.append(out / ".env.example")
    return paths


def _process_setup_cmds(p: DeployProfile) -> str:
    """Return the dependency-install block for a plain process run script."""
    if p.language == "python":
        return textwrap.dedent(f"""\
            if [ -f "venv/Scripts/activate" ]; then
              source venv/Scripts/activate
            elif [ -f "venv/bin/activate" ]; then
              source venv/bin/activate
            elif [ -f ".venv/Scripts/activate" ]; then
              source .venv/Scripts/activate
            elif [ -f ".venv/bin/activate" ]; then
              source .venv/bin/activate
            else
              python3 -m venv .venv 2>/dev/null || true
              source .venv/bin/activate
            fi
            {p.build_cmd}""")
    if p.language == "php":
        return "composer install --no-dev --optimize-autoloader"
    return p.build_cmd


def _process_setup_cmds_windows(p: DeployProfile) -> str:
    """Return the dependency-install block for a Windows .bat run script."""
    if p.language == "python":
        return textwrap.dedent(f"""\
            if exist venv\\Scripts\\activate.bat (
              call venv\\Scripts\\activate.bat
            ) else if exist .venv\\Scripts\\activate.bat (
              call .venv\\Scripts\\activate.bat
            ) else (
              python -m venv .venv 2>nul
              call .venv\\Scripts\\activate.bat
            )
            {p.build_cmd}""")
    if p.language == "php":
        return "composer install --no-dev --optimize-autoloader"
    return p.build_cmd


def _generate_helm(p: DeployProfile, out: Path) -> list[Path]:
    """Generate a full Helm chart skeleton: Chart.yaml, values.yaml, and four templates."""
    helm_dir = out / "helm" / p.project
    tpl_dir = helm_dir / "templates"
    tpl_dir.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []

    mem_k8s = p.estimated_memory.replace("MB", "Mi").replace("GB", "Gi")

    # ── Chart.yaml ────────────────────────────────────────────────────────────
    chart_yaml = textwrap.dedent(f"""\
        # Generated by Zonny — zonny deploy generate --target helm
        apiVersion: v2
        name: {p.project}
        description: Helm chart for {p.project} ({p.language}/{p.framework or 'generic'})
        type: application
        version: 0.1.0
        appVersion: "1.0.0"
    """)
    (helm_dir / "Chart.yaml").write_text(chart_yaml, encoding="utf-8")
    paths.append(helm_dir / "Chart.yaml")

    # ── values.yaml ───────────────────────────────────────────────────────────
    env_values = "\n".join(f'  {v}: ""' for v in p.env_vars) if p.env_vars else "  {}"
    values_yaml = textwrap.dedent(f"""\
        # Default values for {p.project} Helm chart
        replicaCount: 2

        image:
          repository: {p.project}
          pullPolicy: IfNotPresent
          tag: "latest"

        service:
          type: ClusterIP
          port: 80
          targetPort: {p.port}

        ingress:
          enabled: true
          className: "nginx"
          host: {p.project}.example.com

        resources:
          limits:
            memory: {mem_k8s}
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"

        autoscaling:
          enabled: false
          minReplicas: 1
          maxReplicas: 10
          targetCPUUtilizationPercentage: 80

        env:
        {env_values}
    """)
    (helm_dir / "values.yaml").write_text(values_yaml, encoding="utf-8")
    paths.append(helm_dir / "values.yaml")

    # ── templates/_helpers.tpl ────────────────────────────────────────────────
    helpers = textwrap.dedent(f"""\
        {{{{/*
        Expand the name of the chart.
        */}}}}
        {{{{- define "{p.project}.name" -}}}}
        {{{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}}}
        {{{{- end }}}}

        {{{{/*
        Create a default fully qualified app name.
        */}}}}
        {{{{- define "{p.project}.fullname" -}}}}
        {{{{- .Release.Name | trunc 63 | trimSuffix "-" }}}}
        {{{{- end }}}}

        {{{{/*
        Common labels.
        */}}}}
        {{{{- define "{p.project}.labels" -}}}}
        helm.sh/chart: {{{{ .Chart.Name }}}}-{{{{ .Chart.Version }}}}
        app.kubernetes.io/name: {{{{ include "{p.project}.name" . }}}}
        app.kubernetes.io/instance: {{{{ .Release.Name }}}}
        app.kubernetes.io/managed-by: {{{{ .Release.Service }}}}
        {{{{- end }}}}
    """)
    (tpl_dir / "_helpers.tpl").write_text(helpers, encoding="utf-8")
    paths.append(tpl_dir / "_helpers.tpl")

    # ── templates/deployment.yaml ─────────────────────────────────────────────
    env_tmpl = ""
    if p.env_vars:
        env_tmpl = textwrap.dedent("""\
                  env:
                  {{- range $key, $val := .Values.env }}
                    - name: {{ $key }}
                      value: {{ $val | quote }}
                  {{- end }}""")

    deployment_tmpl = textwrap.dedent(f"""\
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {{{{- include "{p.project}.fullname" . }}}}
          labels:
            {{{{- include "{p.project}.labels" . | nindent 4 }}}}
        spec:
          replicas: {{{{ .Values.replicaCount }}}}
          selector:
            matchLabels:
              app.kubernetes.io/name: {{{{ include "{p.project}.name" . }}}}
              app.kubernetes.io/instance: {{{{ .Release.Name }}}}
          template:
            metadata:
              labels:
                app.kubernetes.io/name: {{{{ include "{p.project}.name" . }}}}
                app.kubernetes.io/instance: {{{{ .Release.Name }}}}
            spec:
              containers:
                - name: {{{{ .Chart.Name }}}}
                  image: "{{{{ .Values.image.repository }}}}:{{{{ .Values.image.tag }}}}"
                  imagePullPolicy: {{{{ .Values.image.pullPolicy }}}}
                  ports:
                    - name: http
                      containerPort: {p.port}
                      protocol: TCP
                  resources:
                    {{{{- toYaml .Values.resources | nindent 12 }}}}
                  {env_tmpl}
                  livenessProbe:
                    httpGet:
                      path: /healthz
                      port: http
                    initialDelaySeconds: 30
                    periodSeconds: 10
                  readinessProbe:
                    httpGet:
                      path: /healthz
                      port: http
                    initialDelaySeconds: 5
                    periodSeconds: 5
    """)
    (tpl_dir / "deployment.yaml").write_text(deployment_tmpl, encoding="utf-8")
    paths.append(tpl_dir / "deployment.yaml")

    # ── templates/service.yaml ────────────────────────────────────────────────
    service_tmpl = textwrap.dedent(f"""\
        apiVersion: v1
        kind: Service
        metadata:
          name: {{{{- include "{p.project}.fullname" . }}}}
          labels:
            {{{{- include "{p.project}.labels" . | nindent 4 }}}}
        spec:
          type: {{{{ .Values.service.type }}}}
          ports:
            - port: {{{{ .Values.service.port }}}}
              targetPort: {{{{ .Values.service.targetPort }}}}
              protocol: TCP
              name: http
          selector:
            app.kubernetes.io/name: {{{{ include "{p.project}.name" . }}}}
            app.kubernetes.io/instance: {{{{ .Release.Name }}}}
    """)
    (tpl_dir / "service.yaml").write_text(service_tmpl, encoding="utf-8")
    paths.append(tpl_dir / "service.yaml")

    # ── templates/ingress.yaml ────────────────────────────────────────────────
    ingress_tmpl = textwrap.dedent(f"""\
        {{{{- if .Values.ingress.enabled }}}}
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: {{{{- include "{p.project}.fullname" . }}}}
          labels:
            {{{{- include "{p.project}.labels" . | nindent 4 }}}}
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
        spec:
          ingressClassName: {{{{ .Values.ingress.className }}}}
          rules:
            - host: {{{{ .Values.ingress.host }}}}
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: {{{{- include "{p.project}.fullname" . }}}}
                        port:
                          number: {{{{ .Values.service.port }}}}
        {{{{- end }}}}
    """)
    (tpl_dir / "ingress.yaml").write_text(ingress_tmpl, encoding="utf-8")
    paths.append(tpl_dir / "ingress.yaml")

    return paths
